name: weather_app
description: A new Flutter project.

# Prevents accidental publishing to pub.dev
publish_to: "none"

# Version and build number
version: 1.1.0+3

# Environment
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  injectable: ^2.1.1
  injectable_generator: ^2.1.5
  scroll_snap_list: ^0.9.1
  get_it: ^8.0.3
  build_runner: ^2.2.0
  json_annotation: ^4.9.0
  dio: ^5.0.0
  path_provider: ^2.0.15
  flutter_lints: ^5.0.0
  equatable: ^2.0.5
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9
  retrofit: ^4.0.1
  fluttertoast: ^8.2.2
  rflutter_alert: ^2.0.7
  geocoding: ^3.0.0
  geocoding_ios: ^3.0.1
  geocoding_android: ^3.3.1
  google_geocoding_api: ^1.5.2
  collection: ^1.18.0
  geolocator: ^13.0.4
  geolocator_platform_interface: ^4.2.5
  page_transition: ^2.0.9
  dotted_border: ^2.0.0+3
  image: ^4.0.17
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^6.1.3
  material_symbols_icons: ^4.2719.1
  flutter_bloc: ^9.0.0
  provider: ^6.0.5
  http: ^1.1.0
  localization: ^2.1.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  gap: ^3.0.1
  flutter_secure_storage: ^9.2.4
  permission_handler: ^12.0.0
  local_auth: ^2.1.7
  flutter_screenutil: ^5.9.3
# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

# Flutter launcher icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/ic_sunny.png"
  remove_alpha_ios: true
  background_color_ios: "#71C3FF"
  background_color_android: "#0xff71C3FF"

# Flutter-specific configurations
flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto/static/Roboto-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Roboto/static/Roboto-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Roboto/static/Roboto-Bold.ttf
          weight: 700
  assets:
    - lib/assets/images/
    - lib/assets/images/model/
    - lib/assets/images/ic_sunny.png
    - lib/assets/images/icons/drawable-hdpi/
    - lib/assets/
